baseURL = 'https://blog.arunmalik.dev/'
languageCode = 'en-US'
enableRobotsTXT = true

title = "Shift Happens"
subTitle = "Especially in PROD and it’s always at 3 AM !!"

theme = 'rusty-typewriter'

[author]
name = 'Arun Malik'
avatar = "images/author.jpg"

[rusty_typewriter]
[params.rtwt]
  sidePane = true
  countPageItems = 7 
  searchPath = 'search'
[params.rtwt.home]
  showBio = true
  showAuthorImg = true
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 7
 [params.rtwt.side.home]
  sidePaneSticky = false
  taxonomies = ['tags','series']
  countTaxonomy = 10
 [params.rtwt.side.list]
  sidePaneSticky = false
 [params.rtwt.side.single]
  sidePaneSticky = true 
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 10

[taxonomies]
tag = 'tags'
topic = 'topics'
series = 'series'

[related]
 includeNewer = true
 [[related.indices]]
  name = 'tags'
  weight = 100

[params.social]
  twitter = "https://twitter.com/itsmearunmalik"
  linkedin = "https://www.linkedin.com/in/malik-arun/"
  github = "https://github.com/arun-malik"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
