name: Build and Deploy Hugo Site to GitHub Pages

on:
  push:
    branches: ["main"]  # Or replace "main" with your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3  # Ensure using the latest stable version (v3)
        with:
          submodules: recursive   # Ensures that submodules are also pulled
          fetch-depth: 0          # Fetch full history to get all submodules history

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.146.0'  # Hugo version
          extended: true           # Enable extended version for things like Sass

      - name: Build site
        run: hugo --minify  # Build the site with minification

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Directory to publish (output folder)
